[2025-05-19T08:51:41.316+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nyc_taxi_pipeline.load_data manual__2025-05-19T08:43:58.742681+00:00 [queued]>
[2025-05-19T08:51:41.336+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nyc_taxi_pipeline.load_data manual__2025-05-19T08:43:58.742681+00:00 [queued]>
[2025-05-19T08:51:41.337+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 2
[2025-05-19T08:51:41.358+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): load_data> on 2025-05-19 08:43:58.742681+00:00
[2025-05-19T08:51:41.364+0000] {standard_task_runner.py:60} INFO - Started process 306 to run task
[2025-05-19T08:51:41.369+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'nyc_taxi_pipeline', 'load_data', 'manual__2025-05-19T08:43:58.742681+00:00', '--job-id', '36', '--raw', '--subdir', 'DAGS_FOLDER/nyc_taxi_pipeline.py', '--cfg-path', '/tmp/tmpf1t3yeuv']
[2025-05-19T08:51:41.373+0000] {standard_task_runner.py:88} INFO - Job 36: Subtask load_data
[2025-05-19T08:51:41.438+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-05-19T08:51:41.488+0000] {task_command.py:423} INFO - Running <TaskInstance: nyc_taxi_pipeline.load_data manual__2025-05-19T08:43:58.742681+00:00 [running]> on host dc3ebaf2dadb
[2025-05-19T08:51:42.782+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='nyc_taxi_pipeline' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2025-05-19T08:43:58.742681+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-19T08:43:58.742681+00:00'
[2025-05-19T08:51:42.785+0000] {nyc_taxi_pipeline.py:50} INFO - Starting data loading...
[2025-05-19T08:53:06.909+0000] {local_task_job_runner.py:234} INFO - Task exited with return code -9
[2025-05-19T08:53:07.321+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
